# Generated by Django 5.1.5 on 2025-01-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointmentid', models.AutoField(db_column='appointmentID', primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=10)),
            ],
            options={
                'db_table': 'Appointments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('clientid', models.AutoField(db_column='clientID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phonenumber', models.CharField(blank=True, db_column='phoneNumber', max_length=10, null=True)),
                ('datecreated', models.DateTimeField(auto_now_add=True, db_column='dateCreated')),
            ],
            options={
                'db_table': 'Clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('serviceid', models.AutoField(db_column='serviceID', primary_key=True, serialize=False)),
                ('servicename', models.CharField(db_column='serviceName', max_length=100)),
                ('servicedescription', models.CharField(blank=True, db_column='serviceDescription', max_length=250, null=True)),
                ('active', models.BooleanField(default=True)),
                ('size_options', models.CharField(choices=[('Extra Small', 'Extra Small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Jumbo', 'Jumbo')], default='Medium', max_length=50)),
                ('duration_minutes', models.IntegerField()),
            ],
            options={
                'db_table': 'Services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timeslots',
            fields=[
                ('timeslotid', models.AutoField(db_column='timeslotID', primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('slot_date', models.DateField()),
            ],
            options={
                'db_table': 'Timeslots',
                'managed': False,
            },
        ),
    ]
