# Generated by Django 5.1.5 on 2025-01-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
