# Generated by Django 5.1.5 on 2025-02-08 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_delete_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedBookings',
            fields=[
                ('appointmentID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.appointments')),
                ('clientID', models.IntegerField()),
                ('appointment_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phoneNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('appointment_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed')], default='Confirmed', max_length=10)),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.services')),
            ],
            options={
                'verbose_name_plural': 'Confirmed Bookings',
            },
        ),
    ]
